---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang
  commands:
  - go build ./cmd/skogul

- name: test
  image: golang
  commands:
  - apt-get update
  - apt-get -y install make
  - go get golang.org/x/lint/golint
  - make check
  depends_on:
    - build

- name: prepare-release
  image: golang
  commands:
  - apt-get update
  - apt-get -y install make python3-docutils bzip2 gawk
  - make clean install GIT_DESCRIBE=${DRONE_TAG} DESTDIR=skogul-${DRONE_TAG}
  - make GIT_DESCRIBE=${DRONE_TAG} notes
  - tar cvjf skogul-${DRONE_TAG}.tar.bz2 skogul-${DRONE_TAG}
  depends_on:
    - test
  when:
    event:
    - tag

- name: prepare-centos-release
  image: centos:8
  environment:
    SHELL: /bin/bash
  commands:
  - yum install -y git python3-docutils rpm-build wget make
  - wget https://storage.googleapis.com/golang/getgo/installer_linux
  - chmod +x installer_linux
  - ./installer_linux
  - source /root/.bash_profile
  - make GIT_DESCRIBE=${DRONE_TAG} rpm
  depends_on:
    - prepare-release
  when:
    event:
    - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_api_key
    checksum:
    - sha256
    draft: true
    files:
    - skogul-*.tar.bz2
    - skogul-*.rpm
    note: notes
    title: Skogul ${DRONE_TAG}
  depends_on:
    - prepare-release
    - prepare-centos-release
  when:
    event:
    - tag

...
