#!/bin/bash
# Copyright 2019 Kristian Lyngstøl <kly@kly.no>
#
# Simple wrapper to just run go build/skogul in a loop.

# Alternative implementations would be variations of "trap: sprung!"
# or similar, but this old classic never fails.
ackbar() {
    echo "It's a trap!"
    if [ "x$running" = "x1" ]; then
        echo "lol, nvm"
    else
        echo "They came from.... behind..."
        exit
    fi
}

trap ackbar SIGINT

while true; do
    echo "Ready to build. Press enter to continue"
    read
    echo Building:
    go build github.com/KristianLyng/skogul/pkg/cmd/skogul/ || echo "Failed? L2CODE"
    echo Running
    running=1
    ./skogul
    running=0
    echo "Done"
done
