on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
    - run: make check
      env:
        SKOGUL_TEST_SLEEP_DURATION: 10s
